coverage:
  range: "80..100"
  round: down
  status:
    project:
      default:
        target: auto
        threshold: "80%"
        base: auto
        if_not_found: success
        informational: false
        only_pulls: false
flag_management:
  default_rules:
    carryforward: true
    statuses:
      - type: project
        target: auto
        threshold: 80%
      - type: patch
        target: 80%
  individual_flags:
    - name: backend
      paths:
        - backend
      carryforward: true
      statuses:
        - type: project
          target: 80%
        - type: patch
          target: 80%
    # TODO: when solid-start ready for tests, implement
    # - name: frontend
    #   paths:
    #     - frontend
    #   carryforward: true
    #   statuses:
    #     - type: project
    #       target: 80%
    #     - type: patch
    #       target: 80%
comment:
  layout: "diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  hide_project_coverage: false
github_checks:
  annotations: true
