apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: weather-app-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: "weather-app-weather-app-backend-stripprefix-api@kubernetescrd"
spec:
  rules:
    - host: {{ .Values.host.url | quote }}
      http:
        paths:
          - path: /api
            pathType: ImplementationSpecific
            backend:
              service:
                name: weather-app-backend
                port:
                  name: http
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: weather-app-frontend
                port:
                  name: http
  tls:
    - hosts:
        - {{ .Values.host.url | quote }}
