// Mapping taken from https://open-meteo.com/en/docs
enum WeatherCode {
  Unknown = -1,
  Clear = 0,
  MainlyClear = 1,
  PartlyCloudy = 2,
  Overcast = 3,
  Fog = 45,
  DepositingRimeFog = 48,
  DrizzleLight = 51,
  DrizzleModerate = 53,
  DrizzleDense = 55,
  FreezingDrizzleLight = 56,
  FreezingDrizzleDense = 57,
  RainLight = 61,
  RainModerate = 63,
  RainHeavy = 65,
  FreezingRainLight = 66,
  FreezingRainHeavy = 67,
  SnowLight = 71,
  SnowModerate = 73,
  SnowHeavy = 75,
  SnowGrains = 77,
  RainShowersLight = 80,
  RainShowersModerate = 81,
  RainShowersDense = 82,
  SnowShowersLight = 85,
  SnowShowersHeavy = 86,
  ThunderstormSlightOrModerate = 95,
  ThunderstormHailSlight = 96,
  ThunderstormHailHeavy = 99,
}

export default WeatherCode;
