apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-app-frontend
spec:
  selector:
    matchLabels:
      app: weather-app-frontend
  template:
    metadata:
      labels:
        app: weather-app-frontend
    spec:
      containers:
        - name: weather-app-frontend
          image: "{{ .Values.frontend.image.name }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
          envFrom:
            - secretRef:
                name: weather-app-frontend-config
          resources:
          {{- toYaml .Values.frontend.resources | nindent 12 }}
