apiVersion: v1
kind: Secret
metadata:
  name: weather-app-backend-config
stringData:
  application.yaml: |-
    server:
      port: 8080
    spring:
      datasource:
        url: "jdbc:sqlite:data/data.db"
    backend:
      geo:
        fallback:
          latitude: 50.0911
          longitude: 14.3991
      security:
        argon2:
          enabled: true
          memory: 16384
          parallelism: 2
          iterations: 3
          salt-length: 16
          hash-length: 32
        jwt:
          secret: {{ .Values.backend.config.jwt.secret | quote }}
          expiration-seconds: 3600
          leeway-seconds: 5
