server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: "jdbc:sqlite:data/data.db"
    username: sa
    password:
backend:
  geo:
    fallback:
      latitude: 50.0911
      longitude: 14.3991
  security:
    argon2:
      enabled: true
      memory: 16384
      parallelism: 2
      iterations: 3
      salt-length: 16
      hash-length: 32
    jwt:
      secret: "this-is-not-a-production-secret"
      expiration-seconds: 3600
      leeway-seconds: 5
