server:
  port: 8080
  error:
    whitelabel:
      enabled: false
spring:
  web:
    resources:
      add-mappings: false
  banner:
    location: classpath:banner.txt
  sql:
    init:
      mode: never
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: validate
    open-in-view: false
    generate-ddl: false
  datasource:
    driver-class-name: org.sqlite.JDBC
    #url: "jdbc:sqlite:file::memory:?cache=shared"
    url: "jdbc:sqlite:data.db:?cache=shared"
    username: sa
    password:
  liquibase:
    change-log: "classpath:liquibase/changelog.xml"
backend:
  geo:
    fallback:
      # GPS of the Prague castle
      latitude: 50.0911
      longitude: 14.3990416
  security:
    argon2:
      enabled: true
      memory: 16384
      parallelism: 2
      iterations: 3
      salt-length: 16
      hash-length: 32
