server:
  port: 8080
  error:
    whitelabel:
      enabled: false
spring:
  web:
    resources:
      add-mappings: false
  banner:
    location: classpath:banner.txt
backend:
  geo:
    fallback:
      # GPS of the Prague castle
      latitude: 50.0911
      longitude: 14.3990416
