server:
  port: 8080
  error:
    whitelabel:
      enabled: false
spring:
  web:
    resources:
      add-mappings: false
  banner:
    location: classpath:banner.txt
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
  datasource:
    driver-class-name: org.sqlite.JDBC
    # to use in memory:
    url: jdbc:sqlite:file:data.db:?mode=memory&cache=shared
    # to use a file:
    #url: jdbc:sqlite:file:data.db?cache=shared
    username: sa
    password:
backend:
  geo:
    fallback:
      # GPS of the Prague castle
      latitude: 50.0911
      longitude: 14.3990416
  security:
    argon2:
      enabled: true
      memory: 16384
      parallelism: 2
      iterations: 3
      salt-length: 16
      hash-length: 32
