name: "Build backend"
run-name: "Run ${{github.run_id}}, triggered by ${{github.actor}}"
on:
  pull_request:
    branches:
      - main
permissions:
  pull-requests: write
jobs:
  backend:
    name: "Build backend component"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      # setup
      - name: checkout
        uses: actions/checkout@v4
      - name: setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
          cache-dependency-path: backend/build.gradle.kts
      - name: setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          github-token: "${{secrets.GITHUB_TOKEN}}"
          generate-job-summary: true
          add-job-summary-as-pr-comment: on-failure
          cache-disabled: true
      - name: ensure gradle wrapper is executable
        run: chmod +x gradlew
      # build, run tests and generate codecov
      - name: build and run tests
        run: ./gradlew build
      - name: add code coverage to PR
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: backend/build/reports/jacoco/test/jacocoTestReport.xml
          token: "${{secrets.GITHUB_TOKEN}}"
          title: Code coverage report
          update-comment: true
          fail-emoji: ":x:"
          pass-emoji: ":heavy_check_mark:"
          continue-on-error: true
          min-coverage-overall: 80
          min-coverage-changed-files: 80
      # upload artifacts
      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Package
          path: backend/build/libs
