name: "Build project and publish docker images"
run-name: "Run ${{github.run_id}}, triggered by ${{github.actor}}"
on:
  workflow_dispatch:
  push:
    branches:
      - main
permissions:
  packages: write
  pull-requests: write
jobs:
  backend:
    name: "Build backend component"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    env:
      # will be overwritten in step "repo name lowercase"
      REPO_LOWER: ""
    steps:
      # setup
      - name: checkout
        uses: actions/checkout@v4
      - name: repo name lowercase
        run: echo "REPO_LOWER=$(echo "${{github.repository}}" | tr '[:upper:]' '[:lower:]')" >> ${GITHUB_ENV}
      - name: setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          add-job-summary-as-pr-comment: on-failure
      # create image
      - name: login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io/${{github.repository}}
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
  frontend:
    name: "Build frontend component"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    env:
      # will be overwritten in step "repo name lowercase"
      REPO_LOWER: ""
    steps:
      # setup
      - name: checkout
        uses: actions/checkout@v4
      - name: repo name lowercase
        run: echo "REPO_LOWER=$(echo "${{github.repository}}" | tr '[:upper:]' '[:lower:]')" >> ${GITHUB_ENV}
      # create image
      - name: login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io/${{github.repository}}
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
